### ISSUE TITLE
作者大神您好！

### ISSUE THREAD

**Issue by tjutzdd** [meteorshowers/StereoNet#10]
“1.32 EPE_all with 8X single model 1.48EPE_all with 8X multi model on sceneflow dataset by end-to-end training.”
请问 8X single model 指的是1/8分辨率的未经过分层细化的模型吗？
8X multi model指的是1/8分辨率并且经过多层(3级)细化后的模型吗？
请问作者，经过细化后的模型的错误率(EPE)不是应该比不refine的要低吗？还是小白理解的有问题？请大神指点一二~~~
万分感谢~~~~~~~~

**Comment by meteorshowers** [comment]
@tjutzdd  
是的，refine 后的误差应该更低。
single 的含义是单个refine
