### ISSUE TITLE
构建Cost Volume的问题

### ISSUE THREAD

**Issue by Simon-Ace** [meteorshowers/StereoNet#4]
作者您好，感谢您开源实现的代码

在cost volume构建的时候有些困扰。
为什么只沿着一个维度方向进行平移相减（如代码中沿width方向平移），却没有计算height方向？
```python
for i in range(disp):
        if i > 0:
            cost[:, :, i, :, i:] = refimg_feature[ :, :, :, i:] - targetimg_feature[:, :, :, :-i]
        else:
            cost[:, :, i, :, :] = refimg_feature - targetimg_feature
```

**Comment by zhixuanli** [comment]
@Simon-Ace 
因为y方向已经经过校准，无需计算像素之间的差异，只有在x方向（横向）需要计算两幅图像之间的距离差。

**Comment by Simon-Ace** [comment]
> @Simon-Ace
> 因为y方向已经经过校准，无需计算像素之间的差异，只有在x方向（横向）需要计算两幅图像之间的距离差。

明白了，谢谢
