### ISSUE TITLE
作者您好！请教您关于FPS的问题

### ISSUE THREAD

**Issue by tjutzdd** [meteorshowers/StereoNet#9]
大神您好，我用GTX1060-6G显卡的笔记本跑您的模型，测得FPS=20；用Tesla K80-12G服务器跑您的模型测得FPS=8.，这两台设备跑的速度远达不到您所提到的30-25FPS以及达不到论文里的要求，不知道除了设备自身的问题还有哪些问题可以考虑？  另外，用这个在SceneFlow上的预训练模型做KITTI数据集上的微调得到的效果很差，请问大神，您能否放出微调的部分代码供参考？非常感谢大神！

----再一次表示感谢！蟹蟹~~~

**Comment by meteorshowers** [comment]
@tjutzdd 
这篇文章的速度的确有一定问题，后续我会给出一个详细的分析。
另外，kiit 微调我没有测试过，可以交流下

**Comment by tjutzdd** [comment]
咱们已经是qq好友啦------------------ 原始邮件 ------------------
发件人: "XuanyiLi"<notifications@github.com>
发送时间: 2019年6月11日(星期二) 下午3:18
收件人: "meteorshowers/StereoNet"<StereoNet@noreply.github.com>;
抄送: "tjutzdd"<247838227@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [meteorshowers/StereoNet] 作者您好！请教您关于FPS的问题 (#9)



@tjutzdd
 这篇文章的速度的确有一定问题，后续我会给出一个详细的分析。
 另外，kiit 微调我没有测试过，可以交流下
 
&mdash;
